version: '3.6'
services:
  db:
    image: 'jmrizkallah/epitech_par17:postgres'
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    restart: always
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
  api:
    image: 'jmrizkallah/epitech_par17:api'
    build:
      context : ./ptm_api
    depends_on:
      - db
    environment:
      MIX_ENV: dev
    env_file:
      - .env
    ports:
      - '4000:4000'
    volumes:
      - .:/app
  front:
    image: 'jmrizkallah/epitech_par17:front'
    build:
      context : ./ptm_front
    depends_on:
      - web
    environment:
      MIX_ENV: dev
    env_file:
      - .env
    ports:
      - '8080:8080'
    volumes:
      - .:/front
volumes:
  pgdata: